name: 'Upload to S3'
description: 'Upload files to an AWS S3 bucket'
author: 'Raza Mahmood'
inputs:
  source:
    description: 'A glob pattern of the files to upload'
    required: true
  destination:
    description: 'The destination path in the S3 bucket'
    required: true
  ignore:
    description: 'A glob pattern of files to ignore in the source pattern'
    required: false
    default: ''
  region:
    description: 'The AWS region'
    required: true
  bucket:
    description: 'The name of the S3 bucket'
    required: true
  access_key:
    description: 'The AWS access key id'
    required: true
  secret_key:
    description: 'The AWS secret access key'
    required: true
  clear_destionation:
    description: 'Whether to clear the destination path before uploading'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
